# Use the official Grafana image
FROM grafana/grafana:latest

# Copy provisioning files for datasources and dashboards
COPY provisioning /etc/grafana/provisioning

# Expose the default Grafana port
EXPOSE 3000
