apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-init-scripts
data:
  create_producer_db.sql: |
    {{- .Files.Get "files/create_producer_db.sql" | nindent 4 }}
  create_grafana_db.sql: |
    {{- .Files.Get "files/create_grafana_db.sql" | nindent 4 }}
