apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.password }}
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            - name: pg-data
              mountPath: /var/lib/postgresql/pgdata
      volumes:
        - name: init-scripts
          configMap:
            name: timescaledb-init-scripts
        - name: pg-data
          emptyDir: {}
