apiVersion: v1
kind: Secret
metadata:
  name: timescaledb-credentials
type: Opaque
data:
  POSTGRES_USER: {{ .Values.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.password | b64enc | quote }}
