{
 "title": "All Sensors",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Sensors (last sample)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH ranked_data AS (\n  SELECT\n    sensor_id,\n    value,\n    timestamp,\n    ROW_NUMBER() OVER (PARTITION BY sensor_id ORDER BY timestamp DESC) AS rn\n  FROM\n    sensor_data\n)\nSELECT\n  sensor_id,\n  value\nFROM\n  ranked_data\nWHERE\n  rn = 1;\n"
    }
   ]
  },
  {
   "title": "All Sensors (average)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT sensor_id, AVG(value) FROM sensor_data GROUP BY sensor_id ORDER BY sensor_id ASC LIMIT null "
    }
   ]
  },
  {
   "title": "All Sensors (table)",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT sensor_id, sensor_type, unit FROM sensors LIMIT 50 "
    }
   ]
  },
  {
   "title": "Count (samples)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(value) FROM sensor_data "
    }
   ]
  }
 ]
}