{
 "title": "Fluid Temperature",
 "time": { "from": "2024-12-16T14:26:36.484Z", "to": "2024-12-16T15:56:45.944Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fluid Temperature (last sample)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM sensor_data WHERE sensor_id = 'temperature_fluid' "
    }
   ]
  },
  {
   "title": "Fluid Temperature (time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value FROM sensor_data WHERE sensor_id = 'temperature_fluid' "
    }
   ]
  },
  {
   "title": "Fluid Temperature (last 50 samples)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", value FROM sensor_data WHERE sensor_id = 'temperature_fluid' LIMIT 50 "
    }
   ]
  }
 ]
}