{
 "title": "Power",
 "time": { "from": "2024-12-16T14:26:46.894Z", "to": "2024-12-16T14:43:11.392Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Voltage (last sample)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM sensor_data WHERE sensor_id = 'voltage_motor' "
    }
   ]
  },
  {
   "title": "Voltage (average)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(value) FROM sensor_data WHERE sensor_id = 'voltage_motor' "
    }
   ]
  },
  {
   "title": "Current (last sample)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value FROM sensor_data WHERE sensor_id = 'current_motor' "
    }
   ]
  },
  {
   "title": "Current (average)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(value) FROM sensor_data WHERE sensor_id = 'current_motor' "
    }
   ]
  },
  {
   "title": "Apparent Power (time series)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH voltage AS (\n  SELECT \n    value AS voltage, \n    DATE_TRUNC('second', timestamp) AS voltage_timestamp, \n    LEAD(value) OVER (ORDER BY DATE_TRUNC('second', timestamp)) AS next_voltage\n  FROM sensor_data\n  WHERE sensor_id = 'voltage_motor'\n),\ncurrent AS (\n  SELECT \n    value AS current, \n    DATE_TRUNC('second', timestamp) AS current_timestamp\n  FROM sensor_data\n  WHERE sensor_id = 'current_motor'\n)\nSELECT \n  c.current * v.next_voltage AS power_va,\n  c.current AS current,\n  v.next_voltage AS voltage,\n  c.current_timestamp AS time\nFROM \n  current c\nJOIN \n  voltage v\nON \n  c.current_timestamp = v.voltage_timestamp;\n"
    }
   ]
  }
 ]
}