# Use the official TimescaleDB image
FROM timescale/timescaledb:latest-pg15

# Copy the create db script into the container's initialization directory
# COPY create_producer_db.sql /docker-entrypoint-initdb.d/
# COPY create_grafana_db.sql /docker-entrypoint-initdb.d/
