replicaCount: 2

image:
  repository: docker.io/library/siemens-energy-producer
  tag: "1.0.0"
  pullPolicy: Never

env:
  DB_HOST: "timescaledb"
  DB_PORT: 5432
  DB_NAME: "data_storage"
  DB_USER: "siemens"
  DB_PASSWORD: "energy"
