image:
  repository: docker.io/library/siemens-energy-timescaledb
  tag: "1.0.0"
  pullPolicy: Never

user: "siemens"
password: "energy"

databases:
  - grafana_storage
  - data_storage

storage:
  size: 10Gi
  class: "standard"

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

healthCheckScript: "/usr/local/bin/check_databases.sh"

healthCheck:
  enabled: true
  interval: 5s
  retries: 5
  startPeriod: 5s
  timeout: 5s
