sensors:
  - id: "voltage_motor"
    type: "voltage"
    location: "motor"
    unit: "V"
    interval: 10
    upper_limit: 390 
    lower_limit: 370
  - id: "current_motor"
    type: "current"
    location: "motor"
    unit: "A"
    interval: 10
    upper_limit: 10
    lower_limit: 0.5
  - id: "temperature_motor"
    type: "temperature"
    location: "motor"
    unit: "Celsius"
    interval: 15
    upper_limit: 80
    lower_limit: 0
  - id: "vibration_motor"
    type: "vibration"
    location: "motor"
    unit: "mm/s"
    interval: 9
    upper_limit: 4
    lower_limit: -1.1
  - id: "pressure_suction"
    type: "pressure"
    location: "suction"
    unit: "bar"
    interval: 5 
    upper_limit: 10
    lower_limit: 0
  - id: "pressure_discharge"
    type: "pressure"
    location: "discharge"
    unit: "bar"
    interval: 5
    upper_limit: 15
    lower_limit: 1
  - id: "flow_rate"
    type: "flow"
    location: "discharge"
    unit: "m3/h"
    interval: 5
    upper_limit: 100
    lower_limit: 5
  - id: "temperature_fluid"
    type: "temperature"
    location: "fluid"
    unit: "Celsius"
    interval: 15
    upper_limit: 100
    lower_limit: 0
