apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sensors-config
data:
  {{- range $file, $content := .Files.Glob "files/sensors-*.yaml" }}
  {{ $file | base }}: |
{{ $.Files.Get $file | indent 4 }}
  {{- end }}