apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  selector:
    app: producer  # This should match the label on your StatefulSet pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  # Ensure your producer app is running on this port
