apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer
spec:
  serviceName: "producer"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: [ "/bin/bash", "-c", "sleep infinity" ]
          env:
            - name: DB_HOST
              value: {{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_NAME
              value: {{ .Values.env.DB_NAME }}
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}
            - name: DB_PASSWORD
              value: {{ .Values.env.DB_PASSWORD }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SENSORS_FILE
              value: |
                {{- $default := .Values.defaultSensorsFile }}
                {{- range .Values.sensorsOverrides }}
                {{- if eq (printf "producer-%d" .replica) "$(POD_NAME)" }}
                {{ .file }}
                {{- end }}
                {{- end }}
                {{ $default }}
          volumeMounts:
            - name: sensors-config
              mountPath: /config
      volumes:
        - name: sensors-config
          configMap:
            name: {{ .Release.Name }}-sensors-config
